# Generated by Django 6.0.5 on 2026-06-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200, verbose_name='Doctor Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('image', models.ImageField(upload_to='reviews/', verbose_name='Doctor Image')),
                ('review', models.TextField(verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Show on website')),
            ],
            options={
                'verbose_name': 'Dentist Review',
                'verbose_name_plural': 'Dentist Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
