# Generated by Django 6.0.5 on 2026-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dentistreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentistreview',
            name='city',
        ),
        migrations.AddField(
            model_name='dentistreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Rating (0.0 - 5.0)'),
        ),
        migrations.AlterField(
            model_name='dentistreview',
            name='image',
            field=models.ImageField(upload_to='dentist_image/', verbose_name='Doctor Image'),
        ),
    ]
